{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "nucel.fullname" . }}
  namespace: {{ include "nucel.namespace" . }}
  labels:
    {{- include "nucel.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- range $key, $value := . }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- end }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  {{- if .Values.ingress.tls }}
  tls:
    {{- if kindIs "slice" .Values.ingress.tls }}
    {{- toYaml .Values.ingress.tls | nindent 4 }}
    {{- else }}
    - hosts:
        - {{ .Values.domain }}
      secretName: {{ .Values.ingress.tlsSecretName | default (printf "%s-tls" (include "nucel.fullname" .)) }}
    {{- end }}
  {{- end }}
  rules:
    - host: {{ .Values.domain }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nucel-server
                port:
                  number: {{ .Values.server.port }}
{{- end }}
