{{- if .Values.secrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nucel.secretName" . }}
  namespace: {{ include "nucel.namespace" . }}
  labels:
    {{- include "nucel.labels" . | nindent 4 }}
type: Opaque
stringData:
  NUCEL_DB_USER: {{ .Values.secrets.dbUser | quote }}
  NUCEL_DB_PASS: {{ .Values.secrets.dbPass | quote }}
  NUCEL_CI_RUNNER_TOKEN: {{ .Values.secrets.ciRunnerToken | quote }}
  NUCEL_HOOK_SECRET: {{ .Values.secrets.hookSecret | quote }}
  {{- if .Values.secrets.oidcPrivateKey }}
  NUCEL_OIDC_PRIVATE_KEY: {{ .Values.secrets.oidcPrivateKey | quote }}
  {{- end }}
{{- end }}
---
{{- if and .Values.ciOperator.enabled .Values.secrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: nucel-ci-runner-secret
  namespace: {{ .Values.ciNamespace }}
  labels:
    {{- include "nucel.labels" . | nindent 4 }}
type: Opaque
stringData:
  NUCEL_RUNNER_TOKEN: {{ .Values.ciOperator.runnerToken | default .Values.secrets.ciRunnerToken | quote }}
  NUCEL_API_URL: "http://nucel-server.{{ include "nucel.namespace" . }}.svc.cluster.local:{{ .Values.server.port }}"
{{- end }}
