apiVersion: v1
kind: Service
metadata:
  name: {{ include "agent-operator.fullname" . }}-operator
  namespace: {{ include "agent-operator.namespace" . }}
  labels:
    {{- include "agent-operator.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 9090
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "agent-operator.selectorLabels" . | nindent 4 }}
