---
# Operator ServiceAccount
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "agent-operator.fullname" . }}
  namespace: {{ include "agent-operator.namespace" . }}
  labels:
    {{- include "agent-operator.labels" . | nindent 4 }}
---
# Webhook ServiceAccount
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "agent-operator.fullname" . }}-webhook
  namespace: {{ include "agent-operator.namespace" . }}
  labels:
    {{- include "agent-operator.webhookLabels" . | nindent 4 }}
